# This is a basic workflow to help you get started with Actions

name: My-GithubActions-Basics

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run : echo "Hello world"

  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Pring Hello Message
      run : echo "Hello world from Deploy Job"
   
